# Generated by Django 5.2.1 on 2025-05-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinador',
            options={'verbose_name': 'Coordinador', 'verbose_name_plural': 'Coordinadores'},
        ),
    ]
