# Generated by Django 5.2.1 on 2025-06-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinador', '0002_alter_coordinador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinador',
            options={'verbose_name': 'coordinador', 'verbose_name_plural': 'coordinadores'},
        ),
    ]
