# Generated by Django 5.2.1 on 2025-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinador', '0003_alter_coordinador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de documento'),
        ),
    ]
