# Generated by Django 5.2.1 on 2025-06-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservaservicio', '0002_alter_reservaservicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaservicio',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
    ]
