# Generated by Django 5.2.1 on 2025-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservaservicio', '0003_alter_reservaservicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_evento',
            field=models.DateTimeField(verbose_name='Fecha del evento'),
        ),
    ]
